from typing import Protocol


class GoogleExecuteRequest(Protocol):
    def execute(self) -> dict[str, object]: ...


class DriveFilesApi(Protocol):
    def list(self, **kwargs: object) -> GoogleExecuteRequest: ...

    def get(self, **kwargs: object) -> GoogleExecuteRequest: ...

    def export(self, **kwargs: object) -> object: ...

    def get_media(self, **kwargs: object) -> object: ...


class DriveChangesApi(Protocol):
    def getStartPageToken(  # noqa: N802
        self,
        **kwargs: object,
    ) -> GoogleExecuteRequest: ...

    def list(self, **kwargs: object) -> GoogleExecuteRequest: ...


class DriveService(Protocol):
    def files(self) -> DriveFilesApi: ...

    def changes(self) -> DriveChangesApi: ...


class SheetsValuesApi(Protocol):
    def get(self, **kwargs: object) -> GoogleExecuteRequest: ...

    def update(self, **kwargs: object) -> GoogleExecuteRequest: ...

    def clear(self, **kwargs: object) -> GoogleExecuteRequest: ...


class SheetsSpreadsheetsApi(Protocol):
    def values(self) -> SheetsValuesApi: ...


class SheetsService(Protocol):
    def spreadsheets(self) -> SheetsSpreadsheetsApi: ...
